import { useState, useEffect } from "react";
import { 
  Search, Terminal, FileCode2, Copy, CheckCircle2,
  Code2, ChevronLeft, ChevronRight, RefreshCw
} from "lucide-react";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import adminApi from "@/lib/config";

interface Parameter {
  name: string;
  in: "query" | "path" | "header" | "formData" | "body";
  required?: boolean;
  schema?: Record<string, unknown>;
  description?: string;
}

interface OpenAPIResponse {
  description?: string;
  content?: Record<string, { schema?: Record<string, unknown> }>;
}

interface OpenAPIRequestBody {
  description?: string;
  content?: Record<string, { schema?: Record<string, unknown> }>;
  required?: boolean;
}

interface EndpointDef {
  method: string;
  path: string;
  summary?: string;
  description?: string;
  tags?: string[];
  parameters?: Parameter[];
  requestBody?: OpenAPIRequestBody;
  responses?: Record<string, OpenAPIResponse>;
}

interface OpenAPISpec {
  openapi: string;
  info: {
    title: string;
    version: string;
  };
  paths: Record<string, Record<string, Omit<EndpointDef, "method" | "path">>>;
}

const methodColors: Record<string, string> = {
  get: "bg-blue-100 text-blue-700",
  post: "bg-green-100 text-green-700",
  put: "bg-orange-100 text-orange-700",
  delete: "bg-red-100 text-red-700",
  patch: "bg-yellow-100 text-yellow-700",
};

export default function ApiCheckerPage() {
  const [specs, setSpecs] = useState<OpenAPISpec | null>(null);
  const [endpoints, setEndpoints] = useState<EndpointDef[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [methodFilter, setMethodFilter] = useState("all");
  
  // Pagination
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState<number | "all">(20);

  // Drawer State
  const [selectedEndpoint, setSelectedEndpoint] = useState<EndpointDef | null>(null);
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [copiedCode, setCopiedCode] = useState<string | null>(null);
  
  // Active Code Snippet Tab
  const [activeLang, setActiveLang] = useState<string>("nextjs");

  useEffect(() => {
    fetchSpecs();
  }, []);

  const fetchSpecs = async () => {
    try {
      setLoading(true);
      
      // Let's first try direct backend path if swagger is serving it
      let res;
      try {
        res = await adminApi.get("/docs.json");
      } catch (e) {
         // fallback if swagger ui is at /api/docs and the json is somewhere else or maybe it's not setup to serve purely JSON in our API currently
         // Often it's generated by swagger-jsdoc and passed as a variable to swaggerUi.setup(specs)
         console.error("docs.json not found, ensure your API exposes the raw JSON spec");
      }
      
      if (res && res.data) {
        setSpecs(res.data);
        const parsedEndpoints: EndpointDef[] = [];
        if (res.data.paths) {
          Object.keys(res.data.paths).forEach((path) => {
            const methods = res.data.paths[path];
            Object.keys(methods).forEach((method) => {
               parsedEndpoints.push({
                 method,
                 path,
                 ...methods[method]
               });
            });
          });
        }
        setEndpoints(parsedEndpoints);
      }
    } catch (error) {
      console.error("Failed to load API specs", error);
    } finally {
      setLoading(false);
    }
  };

  const handleSelectEndpoint = (ep: EndpointDef) => {
    setSelectedEndpoint(ep);
    setIsDrawerOpen(true);
    setCopiedCode(null);
    setActiveLang("nextjs"); // Reset tab to default
  };

  const handleSearch = (v: string) => {
    setSearch(v);
    setPage(1);
  };

  const handleLimitChange = (val: string) => {
    if (val === "all") setLimit("all");
    else setLimit(Number(val));
    setPage(1);
  };

  // Compute pagination
  const filteredEndpoints = endpoints.filter(ep => {
    const matchesSearch = ep.path.toLowerCase().includes(search.toLowerCase()) || 
                          ep.tags?.some(t => t.toLowerCase().includes(search.toLowerCase()));
    const matchesMethod = methodFilter === "all" || ep.method.toLowerCase() === methodFilter;
    return matchesSearch && matchesMethod;
  });
  
  const totalItems = filteredEndpoints.length;
  const totalPages = limit === "all" ? 1 : Math.ceil(totalItems / limit);
  const paginatedEndpoints = limit === "all" 
      ? filteredEndpoints 
      : filteredEndpoints.slice((page - 1) * limit, page * limit);


  const generateCodeSnippet = (lang: string) => {
    if (!selectedEndpoint) return "";
    const baseUrl = import.meta.env.VITE_NEXT_PUBLIC_API_URL || "https://api.yourdomain.com";
    const pathUrl = `${baseUrl}${selectedEndpoint.path}`;
    const method = selectedEndpoint.method.toUpperCase();

    switch (lang) {
      case 'nextjs':
        return `// Next.js (App Router / Server Actions)
export async function performAction() {
  const res = await fetch("${pathUrl}", {
    method: "${method}",
    headers: {
      "Content-Type": "application/json",
      "Authorization": \`Bearer \${process.env.API_TOKEN}\`
    }${["POST", "PUT", "PATCH"].includes(method) ? `,\n    body: JSON.stringify({\n      key: "value"\n    })` : ''}
  });

  if (!res.ok) {
    throw new Error('Failed to resolve endpoint');
  }
  
  const data = await res.json();
  return data;
}`;

      case 'vitejs':
        return `// React / Vite.js (Axios)
import axios from 'axios';

const executeRequest = async () => {
  try {
    const response = await axios.${selectedEndpoint.method}(
      "${pathUrl}",
      ${["POST", "PUT", "PATCH"].includes(method) ? `{\n        // payload\n        key: "value"\n      },` : ''}
      {
        headers: {
          'Authorization': \`Bearer \${localStorage.getItem('token')}\`
        }
      }
    );
    console.log("Data:", response.data);
  } catch (error) {
    console.error("API Error:", error);
  }
};`;

      case 'html':
        return `<!-- Vanilla HTML/JS (Fetch API) -->
<script>
  async function callAPI() {
    try {
      const response = await fetch("${pathUrl}", {
        method: "${method}",
        headers: {
          "Content-Type": "application/json",
          "Authorization": "Bearer YOUR_TOKEN"
        }${["POST", "PUT", "PATCH"].includes(method) ? `,\n        body: JSON.stringify({ key: "value" })` : ''}
      });
      
      const data = await response.json();
      console.log(data);
    } catch (err) {
      console.error(err);
    }
  }
</script>`;

      case 'php':
        return `<?php
// PHP (cURL Implementation)
$curl = curl_init();

curl_setopt_array($curl, [
  CURLOPT_URL => "${pathUrl}",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "${method}",
  CURLOPT_HTTPHEADER => [
    "Authorization: Bearer YOUR_TOKEN",
    "Content-Type: application/json"
  ],
]);

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
?>`;

      case 'python':
        return `# Python (Requests Library)
import requests

url = "${pathUrl}"
headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer YOUR_TOKEN"
}

try:
    response = requests.${selectedEndpoint.method}(url, headers=headers${["POST", "PUT", "PATCH"].includes(method) ? `, json={"key": "value"}` : ''})
    response.raise_for_status()
    print("Payload:", response.json())
except requests.exceptions.HTTPError as err:
    print("Execution rejected:", err)`;

      case 'reactnative':
        return `// React Native (Fetch / Async Configuration)
const callMobileAPI = async () => {
  try {
    const response = await fetch("${pathUrl}", {
      method: "${method}",
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
        Authorization: 'Bearer YOUR_TOKEN',
      }${["POST", "PUT", "PATCH"].includes(method) ? `,\n      body: JSON.stringify({\n        key: "value"\n      })` : ''}
    });

    const json = await response.json();
    return json;
  } catch (error) {
    console.error(error);
  }
};`;

      default:
        return "";
    }
  };

  const extractDummyResponse = (responses?: Record<string, OpenAPIResponse>) => {
     if (!responses) return { success: true, message: "Standard operational signal returned." };
     const payload: Record<string, unknown> = { status: "Active" };
     
     if (selectedEndpoint) {
       if (selectedEndpoint.path.includes("id")) {
          payload.id = "60d5ecb8b392d70015383562";
       }
       if (["post", "put"].includes(selectedEndpoint.method)) {
          payload.timestamp = new Date().toISOString();
          payload.environment = "Live Context";
       }
     }
     return payload;
  };

  const handleCopy = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCode(activeLang);
    setTimeout(() => setCopiedCode(null), 2000);
  };

  return (
    <div className="relative flex flex-col bg-white rounded-xl shadow-sm border border-grey-100 mb-6 m-6">
      
      {/* Sidebar: Endpoint List (Master List View) */}
      <div className="w-full flex-col bg-white rounded-xl overflow-hidden">
        <div className="p-4 border-b border-grey-100 flex items-center justify-between">
           <div>
             <h2 className="font-bold text-xl flex items-center gap-2">
               <Terminal className="w-5 h-5 shrink-0 text-primary" /> API Master Catalog
             </h2>
             <p className="text-xs text-grey-400 mt-1">Live Backend Route Definitions & Implementation Guides</p>
           </div>
           {specs && (
             <div className="hidden md:flex flex-col items-end gap-1">
               <Badge variant="outline" className="text-green-600 border-green-200 bg-green-50 font-medium">
                 Systems Active & Online
               </Badge>
               <span className="text-[10px] text-grey-400 font-mono">OpenAPI v{specs.openapi}</span>
             </div>
           )}
        </div>
        
        <div className="p-4 border-b border-grey-100 bg-grey-50/50 flex items-center gap-3">
           <div className="relative flex-1">
             <Search className="w-4 h-4 absolute left-3 top-3.5 text-grey-400" />
             <Input 
               className="pl-9 bg-white border-grey-200" 
               placeholder="Search endpoints by path or tags..." 
               value={search}
               onChange={(e) => handleSearch(e.target.value)}
             />
           </div>
           <div className="flex items-center gap-2 shrink-0">
             <Button
               variant="outline"
               size="sm"
               onClick={fetchSpecs}
               disabled={loading}
               className="h-10 border-grey-200 gap-2 text-grey-600 hover:text-grey-900 shrink-0"
             >
               <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
               <span className="hidden sm:inline">Refresh Models</span>
             </Button>
              <span className="text-sm font-medium text-grey-500 hidden sm:inline">Method:</span>
              <Select value={methodFilter} onValueChange={(val) => { setMethodFilter(val); setPage(1); }}>
                 <SelectTrigger className="w-[100px] h-10 bg-white border-grey-200 text-sm focus:ring-1 focus:ring-primary">
                    <SelectValue placeholder="Method" />
                 </SelectTrigger>
                 <SelectContent>
                    <SelectItem value="all">All</SelectItem>
                    <SelectItem value="get">GET</SelectItem>
                    <SelectItem value="post">POST</SelectItem>
                    <SelectItem value="put">PUT</SelectItem>
                    <SelectItem value="patch">PATCH</SelectItem>
                    <SelectItem value="delete">DELETE</SelectItem>
                 </SelectContent>
              </Select>
              <span className="text-sm font-medium text-grey-500 hidden sm:inline ml-2">Show:</span>
              <Select value={limit.toString()} onValueChange={handleLimitChange}>
                 <SelectTrigger className="w-[100px] h-10 bg-white border-grey-200 text-sm focus:ring-1 focus:ring-primary">
                    <SelectValue placeholder="Limit" />
                 </SelectTrigger>
                 <SelectContent>
                    <SelectItem value="10">10</SelectItem>
                    <SelectItem value="20">20</SelectItem>
                    <SelectItem value="30">30</SelectItem>
                    <SelectItem value="all">All</SelectItem>
                 </SelectContent>
              </Select>
           </div>
        </div>

        <div className="w-full bg-grey-50/20 min-h-[400px]">
           <div className="flex flex-col space-y-2 p-4">
            {loading ? (
               Array.from({length: limit === "all" ? 50 : limit}).map((_, i) => <Skeleton key={i} className="h-14 w-full" />)
            ) : paginatedEndpoints.length > 0 ? (
              paginatedEndpoints.map((ep, idx) => (
                <button
                  key={`${ep.method}-${ep.path}-${idx}`}
                  onClick={() => handleSelectEndpoint(ep)}
                  className={`w-full text-left p-4 rounded-xl text-sm transition flex items-center gap-4 border hover:shadow-md ${
                    selectedEndpoint === ep 
                    ? 'bg-primary/5 border-primary shadow-sm ring-1 ring-primary/20' 
                    : 'bg-white border-grey-100 hover:border-grey-200'
                  }`}
                >
                  <Badge className={`uppercase text-[11px] w-20 justify-center font-bold shrink-0 ${methodColors[ep.method] || 'bg-grey-200'}`}>
                    {ep.method}
                  </Badge>
                  <div className="flex-1 truncate font-mono text-sm text-grey-800 font-semibold" title={ep.path}>
                    {ep.path}
                  </div>
                  <span className="text-grey-400 text-xs truncate max-w-sm hidden lg:block">
                      {ep.summary || "No description mapped"}
                  </span>
                </button>
              ))
            ) : (
               <div className="text-center p-12 text-grey-400 text-sm">No backend routes discovered for this search mapping.</div>
            )}
           </div>
        </div>

        {/* Pagination Footer */}
        {limit !== "all" && totalPages > 1 && (
          <div className="p-4 border-t border-grey-100 bg-white flex items-center justify-between shrink-0 mb-4 rounded-b-xl">
             <div className="text-xs text-grey-500 font-medium">
               Showing {((page - 1) * limit) + 1} to {Math.min(page * limit, totalItems)} of {totalItems} entries
             </div>
             <div className="flex items-center gap-1">
                <Button 
                   variant="outline" 
                   size="sm" 
                   className="h-8 w-8 px-0" 
                   onClick={() => setPage(page - 1)} 
                   disabled={page === 1}
                >
                   <ChevronLeft className="h-4 w-4" />
                </Button>
                
                <div className="hidden sm:flex items-center gap-1">
                   {Array.from({length: Math.min(5, totalPages)}).map((_, i) => {
                      let pageNum = i + 1;
                      // Logic to show pages around current page
                      if (totalPages > 5 && page > 3) {
                         pageNum = page - 2 + i;
                         if (pageNum > totalPages) return null;
                      }
                      
                      return (
                         <Button
                            key={pageNum}
                            variant={page === pageNum ? "default" : "outline"}
                            size="sm"
                            className={`h-8 w-8 px-0 ${page === pageNum ? 'bg-primary text-white' : 'text-grey-600'}`}
                            onClick={() => setPage(pageNum)}
                         >
                            {pageNum}
                         </Button>
                      )
                   })}
                </div>

                <Button 
                   variant="outline" 
                   size="sm" 
                   className="h-8 w-8 px-0" 
                   onClick={() => setPage(page + 1)} 
                   disabled={page >= totalPages}
                >
                   <ChevronRight className="h-4 w-4" />
                </Button>
             </div>
          </div>
        )}
      </div>

      {/* Side Drawer */}
      <Sheet open={isDrawerOpen} onOpenChange={setIsDrawerOpen}>
        <SheetContent className="w-full sm:w-[600px] sm:max-w-[600px] overflow-y-auto flex flex-col p-0">
            {selectedEndpoint && (
              <>
            {/* Drawer Header */}
            <SheetHeader className="p-6 border-b border-grey-100 bg-grey-50 flex-col gap-2 shrink-0">
               <div>
                  <div className="flex items-center gap-3 mb-3">
                     <Badge className={`uppercase text-xs font-bold ${methodColors[selectedEndpoint.method]}`}>
                       {selectedEndpoint.method}
                     </Badge>
                     <Badge variant="outline" className="text-blue-600 border-blue-200 bg-blue-50 font-medium tracking-wide">
                        API Reference
                     </Badge>
                  </div>
                  <SheetTitle className="font-mono font-bold text-grey-900 break-all text-base m-0 leading-tight">
                    {selectedEndpoint.path}
                   </SheetTitle>
               </div>
            </SheetHeader>

            <div className="flex-1 overflow-y-auto p-6 flex flex-col space-y-8 bg-white">
               <div>
                  <h3 className="text-sm font-bold text-grey-900 mb-2 flex items-center gap-2">
                     <FileCode2 className="w-4 h-4 text-grey-400" /> Endpoint Overview
                  </h3>
                  <p className="text-sm text-grey-600 bg-grey-50 p-4 rounded-lg border border-grey-100 leading-relaxed shadow-sm">
                     {selectedEndpoint.description || selectedEndpoint.summary || "No specific technical documentation available for this backend route."}
                  </p>
               </div>
               
               {/* Parameters Table */}
               {selectedEndpoint.parameters && selectedEndpoint.parameters.length > 0 && (
                 <div>
                   <h3 className="text-sm font-bold text-grey-900 mb-3 pb-2 border-b border-grey-100">Required Configuration</h3>
                   <div className="bg-white rounded-lg border border-grey-200 shadow-sm overflow-hidden">
                     <table className="w-full text-left text-sm whitespace-nowrap">
                       <thead className="bg-grey-50 border-b border-grey-200">
                         <tr>
                           <th className="px-4 py-3 font-semibold text-grey-700">Field Name</th>
                           <th className="px-4 py-3 font-semibold text-grey-700">Location</th>
                           <th className="px-4 py-3 font-semibold text-grey-700">Status</th>
                         </tr>
                       </thead>
                       <tbody className="divide-y divide-grey-100">
                         {selectedEndpoint.parameters.map(p => (
                            <tr key={p.name} className="hover:bg-grey-50/50 transition">
                               <td className="px-4 py-3 font-mono text-xs text-blue-600 font-bold">{p.name}</td>
                               <td className="px-4 py-3 text-xs text-grey-500 capitalize">{p.in}</td>
                               <td className="px-4 py-3">
                                 {p.required ? <span className="text-red-500 text-xs font-bold bg-red-50 px-2 py-0.5 rounded">Required</span> : <span className="text-grey-400 text-xs">Optional</span>}
                               </td>
                            </tr>
                         ))}
                       </tbody>
                     </table>
                   </div>
                 </div>
               )}

               {/* Expected Server Responses */}
               {selectedEndpoint.responses && Object.keys(selectedEndpoint.responses).length > 0 && (
                 <div>
                   <h3 className="text-sm font-bold text-grey-900 mb-3 pb-2 border-b border-grey-100">Expected Server Responses</h3>
                   <div className="grid gap-2">
                      {Object.entries<OpenAPIResponse>(selectedEndpoint.responses).map(([code, props]) => (
                         <div key={code} className="flex gap-4 p-3 bg-grey-50 border border-grey-200 rounded-lg shadow-sm items-center">
                            <span className={`font-mono font-extrabold text-sm w-12 shrink-0 ${Number(code) < 400 ? 'text-green-600' : 'text-red-500'}`}>{code}</span>
                            <span className="text-xs text-grey-600 font-medium truncate">{props.description || 'Standard Reply'}</span>
                         </div>
                      ))}
                   </div>
                 </div>
               )}

               {/* Editor Views - Snippet Selector */}
               <div>
                  <h3 className="text-sm font-bold text-grey-900 mb-4 flex items-center gap-2">
                    <Code2 className="w-4 h-4 text-primary" /> Integration Examples
                  </h3>
                  
                  {/* Language Tabs - Flex Wrap Supported */}
                  <div className="flex flex-wrap gap-1.5 mb-3 bg-grey-100 p-1.5 rounded-lg w-full">
                     {[
                       { id: 'nextjs', label: 'Next.js' },
                       { id: 'vitejs', label: 'Vite.js / React' },
                       { id: 'html', label: 'HTML / Core JS' },
                       { id: 'php', label: 'PHP' },
                       { id: 'python', label: 'Python' },
                       { id: 'reactnative', label: 'React Native' }
                     ].map(tab => (
                        <button
                          key={tab.id}
                          onClick={() => setActiveLang(tab.id)}
                          className={`text-[12px] px-3.5 py-1.5 rounded-md font-medium transition-all ${
                            activeLang === tab.id 
                            ? 'bg-white shadow-sm text-grey-900 ring-1 ring-grey-200' 
                            : 'text-grey-500 hover:text-grey-700 hover:bg-grey-200/50'
                          }`}
                        >
                           {tab.label}
                        </button>
                     ))}
                  </div>

                  {/* Dark Editor View for Code Snippet */}
                  <div className="rounded-xl overflow-hidden shadow-xl border border-grey-800 bg-[#1e1e1e] flex flex-col">
                     {/* Editor Top Bar (Mac Traffic Lights) */}
                     <div className="flex items-center justify-between px-4 py-3 border-b border-grey-700 bg-[#2d2d2d] shrink-0">
                        <div className="flex gap-2 shrink-0">
                           <div className="w-3 h-3 rounded-full bg-[#ff5f56]"></div>
                           <div className="w-3 h-3 rounded-full bg-[#ffbd2e]"></div>
                           <div className="w-3 h-3 rounded-full bg-[#27c93f]"></div>
                        </div>
                        <span className="text-[#a0a0a0] text-[11px] font-mono tracking-wider ml-4 truncate">{activeLang}.script</span>
                        
                        <button 
                           onClick={() => handleCopy(generateCodeSnippet(activeLang))}
                           className="ml-auto flex shrink-0 items-center gap-1.5 text-xs text-grey-400 hover:text-white transition group"
                        >
                           {copiedCode === activeLang ? (
                             <><CheckCircle2 className="w-3.5 h-3.5 text-green-400" /> <span className="text-green-400 hidden sm:inline">Copied</span></>
                           ) : (
                             <><Copy className="w-3.5 h-3.5 group-hover:scale-110 transition-transform" /> <span className="hidden sm:inline">Copy Snippet</span></>
                           )}
                        </button>
                     </div>
                     <pre className="p-4 sm:p-5 text-[12px] sm:text-[13px] font-mono leading-relaxed text-[#e4e4e4] overflow-x-auto min-h-[220px]">
                        <code>{generateCodeSnippet(activeLang)}</code>
                     </pre>
                  </div>
               </div>

               {/* Editor View - Dummy Response Structural Preview */}
               <div>
                  <h3 className="text-sm font-bold text-grey-900 mb-3 pb-2 border-b border-grey-100">Theoretical Response Payload</h3>
                  <div className="rounded-xl overflow-hidden border border-grey-200 shadow-sm bg-[#09090b] flex flex-col">
                     {/* Editor Top Bar (Response) */}
                     <div className="flex items-center px-4 py-3 border-b border-grey-800 bg-[#18181b] shrink-0">
                        <span className="text-[#a1a1aa] text-[11px] sm:text-xs font-mono font-medium flex items-center gap-2">
                           <span className="w-2 h-2 rounded-full bg-green-500 shadow-[0_0_8px_rgba(34,197,94,0.6)]"></span> Output Evaluation Structure
                        </span>
                     </div>
                     <pre className="p-4 sm:p-5 text-[11px] sm:text-[12px] font-mono text-[#a1a1aa] overflow-hidden whitespace-pre-wrap">
                        {JSON.stringify(extractDummyResponse(selectedEndpoint.responses), null, 2)}
                     </pre>
                  </div>
               </div>

            </div>
              </>
            )}
        </SheetContent>
      </Sheet>
      
    </div>
  );
}
